### ISSUE TITLE
Sporadic mpv traceback

### ISSUE THREAD

**Issue by Luni-4** [bubblesub/bubblesub#71]
Sometimes I get the following traceback opening `bubblesub`. I'm using the master branch version of `mpv`

```
2020-01-14 14:06:01.892472 [e] 'method' object is not connected
2020-01-14 14:06:01.893320 [e] Traceback (most recent call last):
2020-01-14 14:06:01.893493 [e]   File "/usr/local/lib/python3.7/dist-packages/bubblesub/api/log.py", line 110, in exception_guard
2020-01-14 14:06:01.894136 [e]     yield
2020-01-14 14:06:01.894365 [e]   File "/usr/local/lib/python3.7/dist-packages/bubblesub/ui/mpv.py", line 274, in _mpv_event_handler
2020-01-14 14:06:01.896544 [e]     if self._handle_event(event):
2020-01-14 14:06:01.897389 [e]   File "/usr/local/lib/python3.7/dist-packages/bubblesub/ui/mpv.py", line 344, in _handle_event
2020-01-14 14:06:01.899890 [e]     self._on_pause_change
2020-01-14 14:06:01.901375 [e] TypeError: 'method' object is not connected
```

**Comment by rr-** [comment]
Thanks for the report. Could you share some details? What are you doing when you experience this problem?

**Comment by Luni-4** [comment]
The traceback happens as soon as I open `bubblesub`. After this error has appeared, I closed bubblesub

**Comment by rr-** [comment]
Could you please verify whether this problem occurs on the latest stable mpv version? Cause I can't say I have run into it

**Comment by Luni-4** [comment]
I re-installed `mpv` from scratch and the problem seems solved. Sometimes I get `'bubblesub' terminated by signal SIGSEGV (Address boundary error)` but I think it's related to #56.

`

**Comment by rr-** [comment]
This is the same only if the crash happens during a normal program exit.

**Comment by Luni-4** [comment]
> This is the same only if the crash happens during a normal program exit.

Exactly, it happens during a normal program exit.
