### ISSUE TITLE
Traceback on exit after using spellcheck

### ISSUE THREAD

**Issue by Subarashii-no-Fansub** [bubblesub/bubblesub#81]
Hello
After using the spellcheck and then exiting bubblesub I have this exception in log:
```
Exception ignored in: <function Dict.__del__ at 0x7f441d9a1b80>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/enchant/__init__.py", line 556, in __del__
  File "/usr/lib/python3.9/site-packages/enchant/__init__.py", line 614, in _free
  File "/usr/lib/python3.9/site-packages/enchant/__init__.py", line 322, in _free_dict
  File "/usr/lib/python3.9/site-packages/enchant/__init__.py", line 329, in _free_dict_data
TypeError: 'NoneType' object is not callable
```
Cheers

**Comment by rr-** [comment]
I'd say it's a problem with the enchant library, not us
